services:
  - type: web
    name: nexora-erp
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: NEXORA_JWT_SECRET
        generateValue: true
      - key: DATABASE_HOST
        fromDatabase:
          name: nexora-erp-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: nexora-erp-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: nexora-erp-db
          property: database
      - key: DATABASE_USER
        fromDatabase:
          name: nexora-erp-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: nexora-erp-db
          property: password

databases:
  - name: nexora-erp-db
    databaseName: nexora_erp
    user: nexora
    plan: free
