spring.datasource.url=jdbc:postgresql://localhost:5432/nexora_erp
spring.datasource.username=nexora
spring.datasource.password=nexora
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
