CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    document VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(30),
    registration_date DATE NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_customers_document ON customers (document);
CREATE INDEX idx_customers_name ON customers (name);
