CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    sku VARCHAR(60) NOT NULL,
    price NUMERIC(15, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    minimum_stock INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX uk_products_sku ON products (sku);
CREATE INDEX idx_products_name ON products (name);
